/* eslint-disable @typescript-eslint/no-require-imports -- Standalone offline Playwright runner. */
// API fixtures are generated by ConsGroupCrm/tests/MiniAppCatalogSmoke.cs. No production traffic is allowed.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const path = require('node:path');
const fixtures = require('./catalog-fixtures.json');
async function main() {
  const server = spawn(process.execPath, [path.resolve('node_modules/vite/bin/vite.js'), 'preview', '--host', '127.0.0.1', '--port', '4180', '--strictPort'], { stdio: 'pipe' });
  let browser, page;
  try {
    await new Promise((resolve, reject) => { server.stdout.on('data', d => { if (String(d).includes('4180')) resolve(); }); server.on('error', reject); server.on('exit', c => reject(Error(`Preview exited ${c}`))); setTimeout(() => reject(Error('Preview timeout')), 10000).unref(); });
    browser = await chromium.launch({ headless: true, channel: process.platform === 'win32' ? 'msedge' : undefined });
    const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
    await context.addInitScript(() => { window.TelegramWebviewProxy = { postEvent(name) { if (name === 'web_app_request_viewport') setTimeout(() => window.dispatchEvent(new MessageEvent('message', { data: JSON.stringify({ eventType: 'viewport_changed', eventData: { height: 844, is_state_stable: true, is_expanded: true } }) })), 0); } }; });
    const errors = [], external = [], calls = [], records = new Map();
    let documentUploaded = false, isAdmin = true, catalogFailure = false;
    await context.route('**/*', async route => {
      const url = new URL(route.request().url());
      if (url.hostname === '127.0.0.1') return route.continue();
      if (url.hostname !== 'unit-control.ru' || !url.pathname.startsWith('/MiniApp/')) { external.push(url.href); return route.abort(); }
      assert.ok(route.request().headers()['x-telegram-init-data']);
      const action = url.pathname.split('/').pop();
      const body = action === 'UploadCampaignDocument' ? { Multipart: route.request().postData() } : route.request().postDataJSON();
      calls.push({ action, body });
      let data;
      const fixture = fixtures.find(x => x.Definition.Kind === body.Kind);
      if (fixture && !records.has(body.Kind)) records.set(body.Kind, { Id: 100 + fixtures.indexOf(fixture), Revision: 'v1', Values: { ...fixture.Values } });
      switch (action) {
        case 'Me': data = { ManagerId: 12, CompanyId: 8, Name: 'Тестовый менеджер', Permissions: { Clients: true, Events: true, Missions: true, EditClients: true, EditEvents: true, Messages: true, Reports: true, Finance: true, Payments: isAdmin, Notifications: true, IsAdmin: isAdmin } }; break;
        case 'Lookups': data = { Managers: [], Adsources: [], EventTypes: [], EventStatuses: [], Services: [] }; break;
        case 'CatalogSections':
          if (catalogFailure) return route.fulfill({ json: { Success: false, ErrMsg: 'Тестовый сбой связи' }, headers: { 'Access-Control-Allow-Origin': '*' } });
          data = { Items: fixtures.map(x => x.Definition).filter(x => !x.ParentField && (isAdmin || x.Kind === 'services')) }; break;
        case 'Calendar': data = { datepickfrom: body.datepickfrom || '2026-09-01T00:00:00', Slots: [] }; break;
        case 'CatalogList': data = { Definition: fixture.Definition, Page: 1, Total: records.get(body.Kind) ? 1 : 0, Items: records.get(body.Kind) ? [records.get(body.Kind)] : [] }; break;
        case 'CatalogDetails': data = { Definition: fixture.Definition, Item: body.Id ? records.get(body.Kind) : { Id: 0, Revision: null, Values: { ...fixture.Values } } }; break;
        case 'SaveCatalog': assert.ok(body.RequestId); records.set(body.Kind, { Id: 100 + fixtures.indexOf(fixture), Revision: 'v2', Values: body.Values }); data = { Id: records.get(body.Kind).Id }; break;
        case 'DeleteCatalog': records.set(body.Kind, null); data = { Id: body.Id }; break;
        case 'CampaignDocuments': data = { Items: documentUploaded ? [{ Id: 1, Name: 'test.txt', Size: 10 }] : [] }; break;
        case 'UploadCampaignDocument': assert.match(body.Multipart, /RequestId/); documentUploaded = true; data = { Id: 1 }; break;
        case 'DownloadCampaignDocument': return route.fulfill({ body: 'test file', contentType: 'application/octet-stream', headers: { 'Access-Control-Allow-Origin': '*' } });
        case 'EmployeeAccount': data = {}; break;
        case 'Exams': data = { Items: [{ Id: 1, Name: 'Тест сотрудника', Comments: '', AttemptsLeft: 5, BestPercent: 0 }], History: [] }; break;
        case 'ExamQuestions': data = { Id: 1, Name: 'Тест сотрудника', Revision: 'protected', Questions: [{ Id: 1, Name: 'Выберите вариант', Answers: [{ Id: 10, Name: 'Первый' }, { Id: 11, Name: 'Второй' }] }] }; break;
        case 'SubmitExam': assert.deepEqual(body.Answers, [10]); assert.equal(body.Revision, 'protected'); assert.ok(body.RequestId); data = { Percent: 100, CorrectCount: 1, QuestionCount: 1 }; break;
        case 'BulkHistory': data = { Page: 1, Total: 1, Items: [{ Id: 1, MessageText: 'Тестовая рассылка', Created: '2026-09-11T12:00:00', Total: 1, Delivered: 0, Failed: 0, Pending: 1 }], Recipients: [{ ClientId: 71, Sent: false, Failed: false, Error: null }] }; break;
        case 'PreviewBulk': assert.deepEqual(body.ClientIds, [71]); data = { Targets: [{ Id: 71, Name: 'Клиент', TelegramId: 123456, Bot: 'ASHFXPRO' }], Count: 1, Skipped: 0, PreviewHash: 'preview' }; break;
        case 'SendBulk': assert.equal(body.PreviewHash, 'preview'); assert.ok(body.RequestId); data = { Id: 1 }; break;
        case 'AuditLog': data = { Page: 1, Total: 1, Items: [{ Id: 1, Created: '2026-09-11T12:00:00', UserLogin: 'test', ActionType: 'Update', EntityType: 'Service', EntityId: 100, EntityName: 'Тариф', Property: 'Name', OldValue: 'Было', NewValue: 'Стало' }] }; break;
        case 'BotStream': data = { Items: [{ Key: 'out:1', ClientId: 71, ClientName: 'Клиент', ChatId: 123456, Text: 'Сообщение бота', Source: 'ASHFXPRO', Status: 'Отправлено', Created: '2026-09-11T12:00:00' }] }; break;
        default: throw Error(`Unexpected endpoint ${action}`);
      }
      await route.fulfill({ json: { Success: true, ...data }, headers: { 'Access-Control-Allow-Origin': '*' } });
    });
    page = await context.newPage(); page.setDefaultTimeout(10000); page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept());
    const launch = new URLSearchParams({ tgWebAppPlatform: 'tdesktop', tgWebAppVersion: '8.0', tgWebAppThemeParams: JSON.stringify({ bg_color: '#ffffff', text_color: '#222222', button_color: '#2481cc', button_text_color: '#ffffff' }), tgWebAppData: new URLSearchParams({ user: JSON.stringify({ id: 123, first_name: 'Test' }), auth_date: String(Math.floor(Date.now() / 1000)), hash: 'test-only' }).toString() });
    const go = async route => page.goto(`http://127.0.0.1:4180/ucminiapp/${route}#${launch}`);
    await go('');
    const home = page.locator('main');
    await home.getByRole('link', { name: 'Тарифы', exact: true }).waitFor();
    assert.equal(await page.locator('.section-tile--primary').count(), 6);
    for (const [name, path] of [['Календарь', '/calendar'], ['Клиенты', '/clients'], ['События', '/events'], ['Уведомления', '/notifications'], ['Отчеты', '/reports'], ['Платежи от клиентов', '/payments']]) {
      assert.equal(await home.getByRole('link', { name, exact: true }).getAttribute('href'), '/ucminiapp' + path);
    }
    assert.equal(await page.locator('.section-tile--secondary').count(), fixtures.filter(x => !x.Definition.ParentField).length + 6);
    assert.ok((await page.locator('.section-tile--primary svg').first().boundingBox()).width > (await page.locator('.section-tile--secondary svg').first().boundingBox()).width);
    for (const width of [320, 390, 1280]) {
      await page.setViewportSize({ width, height: 844 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Home width ' + width);
      if (width === 390) await page.screenshot({ path: 'tests/home-mobile.png', fullPage: true });
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => { for (const [key, value] of Object.entries({ 'bg-color': '#17212b', 'secondary-bg-color': '#0e1621', 'text-color': '#f5f5f5', 'hint-color': '#a0aab6', 'link-color': '#78bcf3', 'section-separator-color': '#344354' })) document.documentElement.style.setProperty('--tg-theme-' + key, value); });
    await page.screenshot({ path: 'tests/home-dark.png', fullPage: true, animations: 'disabled' });
    await home.getByRole('link', { name: 'Календарь', exact: true }).click();
    await page.getByText('Нет записей в этом периоде.').waitFor();
    await page.getByRole('button', { name: '→', exact: true }).click();
    await page.waitForURL(/calendar\?month=2026-10/);
    await page.getByRole('link', { name: 'Главная', exact: true }).click();
    await home.getByRole('link', { name: 'Календарь', exact: true }).waitFor();
    isAdmin = false; await page.reload();
    await home.getByRole('link', { name: 'Тарифы', exact: true }).waitFor();
    assert.equal(await home.getByRole('link', { name: 'Платежи от клиентов', exact: true }).count(), 0);
    assert.equal(await home.getByRole('link', { name: 'Журнал действий', exact: true }).count(), 0);
    assert.equal(await home.getByRole('link', { name: 'Сотрудники', exact: true }).count(), 0);
    isAdmin = true; catalogFailure = true; await page.reload();
    await page.getByRole('alert').waitFor();
    assert.equal(await page.locator('.section-tile--primary').count(), 6);
    catalogFailure = false; await page.getByRole('button', { name: 'Повторить', exact: true }).click();
    await home.getByRole('link', { name: 'Тарифы', exact: true }).waitFor();
    await go('catalog'); await page.getByRole('heading', { name: 'Остальные разделы CRM' }).waitFor();
    for (const { Definition: d } of fixtures) {
      await go(`catalog/${d.Kind}`); await page.getByRole('heading', { name: d.Title, exact: true }).waitFor();
      if (d.CanCreate) await page.getByRole('link', { name: 'Создать', exact: true }).click();
      else { await page.locator('.record-card').first().click(); await page.getByRole('button', { name: 'Изменить', exact: true }).click(); }
      await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
      await page.getByRole('button', { name: 'Изменить', exact: true }).waitFor();
      assert.ok(calls.some(x => x.action === 'SaveCatalog' && x.body.Kind === d.Kind), `Save ${d.Kind}`);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, `Mobile width ${d.Kind}`);
    }
    await go('catalog/campaigns/101');
    await page.getByLabel('Файл до 10 МБ').setInputFiles({ name: 'test.txt', mimeType: 'text/plain', buffer: Buffer.from('test file') });
    await page.getByRole('button', { name: 'Загрузить документ' }).click();
    const download = page.waitForEvent('download'); await page.getByRole('button', { name: /test.txt/ }).click(); await download;
    await go('catalog/managers/103'); await page.getByText('Учётная запись CRM', { exact: true }).click();
    await page.getByLabel('Новый пароль').fill('Test-password-only-42'); await page.getByRole('button', { name: 'Сохранить пароль' }).click();
    await page.getByText('Учётная запись обновлена.').waitFor();
    await go('catalog/adsources/105'); await page.getByRole('button', { name: 'Удалить', exact: true }).click(); await page.getByText('Записей нет.', { exact: true }).waitFor();
    await go('exams'); await page.getByRole('button', { name: 'Пройти тест' }).click(); await page.getByLabel('Первый', { exact: true }).check(); await page.getByRole('button', { name: 'Завершить тест' }).click(); await page.getByText('Результат: 100%').waitFor();
    await go('bulk'); await page.getByLabel('ID клиентов (до 500)').fill('71, 71'); await page.getByLabel('Текст сообщения').fill('Тестовая рассылка'); await page.getByRole('button', { name: 'Проверить получателей' }).click(); await page.getByRole('button', { name: 'Запустить рассылку' }).click(); await page.getByText('Рассылка №1 поставлена в очередь.').waitFor();
    await page.getByRole('button', { name: 'Статусы клиентов' }).click(); await page.getByRole('link', { name: 'Клиент №71' }).waitFor();
    await go('audit'); await page.getByText('Было → Стало').waitFor();
    await go('bot-stream'); await page.getByText('Сообщение бота', { exact: true }).waitFor();
    await go('catalog'); await page.getByRole('heading', { name: 'Остальные разделы CRM' }).waitFor(); await page.screenshot({ path: 'tests/catalog-mobile.png', fullPage: true });
    assert.deepEqual(errors, []); assert.deepEqual(external, []);
    console.log(`PASS: ${fixtures.length} catalog forms, home tiles/navigation/permissions/mobile layouts, company settings, campaign document upload/download, employee account, deletion, exam, broadcast preview/confirmation, audit and bot stream; all requests mocked.`);
  } catch (e) { if (page) { console.error(await page.locator('body').innerText()); await page.screenshot({ path: 'tests/catalog-failure.png', fullPage: true }); } throw e; }
  finally { if (browser) await browser.close(); server.kill(); }
}
main().catch(e => { console.error(e); process.exitCode = 1; });
